apiVersion: v1
kind: ConfigMap
metadata:
  name: gogs-ini-tmpl
  namespace: gogs
data:
  app.tmpl.ini: |
    BRAND_NAME = ${BRAND_NAME}
    RUN_USER = git
    RUN_MODE = prod

    [database]
    TYPE     = ${DB_TYPE}
    HOST     = ${DB_HOST}
    NAME     = ${DB_NAME}
    USER     = ${DB_USER}
    PASSWORD = ${DB_PASS}
    SSL_MODE = disable
    PATH     = data/gogs.db

    [repository]
    ROOT = /data/git/gogs-repositories

    [server]
    DOMAIN           = localhost
    HTTP_PORT        = 3000
    ROOT_URL         = http://localhost:3000/
    DISABLE_SSH      = false
    SSH_PORT         = 22
    START_SSH_SERVER = false
    OFFLINE_MODE     = false

    [email]
    ENABLED = false

    [auth]
    ACTIVATE_CODE_LIVES                     = 180
    RESET_PASSWORD_CODE_LIVES               = 180
    REQUIRE_EMAIL_CONFIRMATION              = false
    REQUIRE_SIGNIN_VIEW                     = false
    DISABLE_REGISTRATION                    = false
    ENABLE_REGISTRATION_CAPTCHA             = true
    ENABLE_REVERSE_PROXY_AUTHENTICATION     = false
    ENABLE_REVERSE_PROXY_AUTO_REGISTRATION  = false
    REVERSE_PROXY_AUTHENTICATION_HEADER     = X-WEBAUTH-USER

    [user]
    ENABLE_EMAIL_NOTIFICATION = false

    [picture]
    DISABLE_GRAVATAR        = false
    ENABLE_FEDERATED_AVATAR = true

    [session]
    PROVIDER = file

    [log]
    MODE      = file
    LEVEL     = Info
    ROOT_PATH = /app/gogs/log

    [security]
    INSTALL_LOCK = false
    SECRET_KEY   = VGhpcy1pcy0xLXN0cm9uZy1wYXNzd29yZCE=
