apiVersion: v1
kind: ConfigMap
metadata:
  name: gogs-ini-tmpl
  namespace: gogs
data:
  app.tmpl.ini: |
    BRAND_NAME = ${BRAND_NAME}
    RUN_USER = git
    RUN_MODE = prod

    [database]
    TYPE     = ${DB_TYPE}
    HOST     = ${DB_HOST}
    NAME     = ${DB_NAME}
    USER     = ${DB_USER}
    PASSWORD = ${DB_PASS}
    SSL_MODE = disable
    PATH     = data/gogs.db

    [repository]
    ROOT = /data/git/gogs-repositories
    DEFAULT_BRANCH = master

    [repository.upload]
    FILE_MAX_SIZE = 10
    MAX_FILES = 5

    [server]
    DOMAIN           = git.dave-vlab.corp
    HTTP_PORT        = 3000
    ROOT_URL         = http://localhost:3000/
    DISABLE_SSH      = false
    SSH_PORT         = 22
    START_SSH_SERVER = false
    OFFLINE_MODE     = false
    EXTERNAL_URL     = https://git.dave-vlab.corp/

    [email]
    ENABLED = true
    HOST    = miab.dave-vlab.corp:587
    FROM    = "Gogs" <alert@dave-vlab.com>
    USER    = alert@dave-vlab.com
    PASSWORD = budhab-zahtom-7koxqU
    SKIP_VERIFY = true

    [auth]
    ACTIVATE_CODE_LIVES                     = 180
    RESET_PASSWORD_CODE_LIVES               = 180
    REQUIRE_EMAIL_CONFIRMATION              = true
    REQUIRE_SIGNIN_VIEW                     = false
    DISABLE_REGISTRATION                    = false
    ENABLE_REGISTRATION_CAPTCHA             = true
    ENABLE_REVERSE_PROXY_AUTHENTICATION     = false
    ENABLE_REVERSE_PROXY_AUTO_REGISTRATION  = false
    REVERSE_PROXY_AUTHENTICATION_HEADER     = X-WEBAUTH-USER

    [user]
    ENABLE_EMAIL_NOTIFICATION = true

    [picture]
    DISABLE_GRAVATAR        = false
    ENABLE_FEDERATED_AVATAR = true

    [session]
    PROVIDER = file

    [attachment]
    MAX_SIZE = 10
    MAX_FILES = 5

    [log]
    MODE      = file
    LEVEL     = Info
    ROOT_PATH = /app/gogs/log

    [security]
    INSTALL_LOCK = true
    SECRET_KEY   = VGhpcy1pcy0xLXN0cm9uZy1wYXNzd29yZCE=
