apiVersion: v1
kind: Service
metadata:
  name: gogs
  namespace: gogs
  labels:
    app: gogs
    service: gogs
  annotations:
    'prometheus.io/scrape': 'true'
spec:
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: gogs
    service: gogs
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogs
  namespace: gogs
  labels:
    app: gogs
    service: gogs
spec:
  serviceName: gogs
  replicas: 1
  selector:
    matchLabels:
      app: gogs
      service: gogs
  template:
    metadata:
      labels:
        app: gogs
        service: gogs
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: generate-gogs-config
        image: scottbeca/envsubst:latest
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: gogs-ini
              key: app_name
        - name: DB_TYPE
          valueFrom:
            configMapKeyRef:
              name: gogs-ini
              key: db_type
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: gogs-ini
              key: db_host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: gogs-ini
              key: db_name
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: gogs-ini
              key: db_user
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              name: gogs-ini
              key: db_pass
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              name: gogs-ini
              key: db_pass
        # - name: OUTPUT_DESTINATION
        #   value: /gogs-config/app.ini
        volumeMounts:
        - name: gogs-ini-tmpl
          mountPath: /workdir
        - name: gogs-config-dir
          mountPath: /processed
      containers:
      - name: gogs
        image: gogs/gogs
        command:
        - sh
        - -c
        - '/app/gogs/docker/start.sh cp -f /gogs-config/app.tmpl.ini /data/gogs/conf/app.ini && chown -R git:git /data/gogs/conf && /bin/s6-svscan /app/gogs/docker/s6/'
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 3000
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 1
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: "0.5"
        volumeMounts:
        - name: gogs-data
          mountPath: /data
        - name: gogs-config-dir
          mountPath: /gogs-config
      restartPolicy: Always
      volumes:
      - name: gogs-ini-tmpl
        configMap:
          name: gogs-ini-tmpl
      - name: gogs-config-dir
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: gogs-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
